# Generated by Django 6.0.1 on 2026-01-26 21:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Gallery Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('gallery_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10, verbose_name='Gallery Type')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Is Favorite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='Shared At')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can Edit')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='gallery.gallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Share',
                'verbose_name_plural': 'Gallery Shares',
                'ordering': ['-shared_at'],
                'unique_together': {('gallery', 'user')},
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_galleries', through='gallery.GalleryShare', to=settings.AUTH_USER_MODEL, verbose_name='Shared With'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Tag name (case-insensitive, normalized)', max_length=100, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(help_text='URL-friendly tag identifier', max_length=100, unique=True, verbose_name='Tag Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this tag is used across all objects', verbose_name='Usage Count')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='gallery_tag_name_2a271b_idx'), models.Index(fields=['slug'], name='gallery_tag_slug_90ef48_idx')],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for the gallery', related_name='galleries', to='gallery.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Album Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('exif_metadata', models.JSONField(blank=True, default=dict, help_text='EXIF metadata extracted from pictures')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='gallery.gallery', verbose_name='Gallery')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for the album', related_name='albums', to='gallery.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('seaweedfs_file_id', models.CharField(help_text='File ID from SeaweedFS', max_length=100, unique=True, verbose_name='SeaweedFS File ID')),
                ('seaweedfs_url', models.URLField(blank=True, help_text='Full URL to file in SeaweedFS', max_length=500, verbose_name='SeaweedFS URL')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100, verbose_name='MIME Type')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (px)')),
                ('ai_tags', models.JSONField(blank=True, default=list, help_text='Tags generated by AI (YOLO)')),
                ('ocr_text', models.TextField(blank=True, help_text='Text extracted by OCR (PaddleOCR)')),
                ('exif_data', models.JSONField(blank=True, default=dict, help_text='EXIF metadata from the image')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Is Favorite')),
                ('taken_at', models.DateTimeField(blank=True, help_text='Date/time when photo was taken (from EXIF)', null=True, verbose_name='Taken At')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='gallery.album', verbose_name='Album')),
                ('tags', models.ManyToManyField(blank=True, help_text='User-defined tags', related_name='pictures', to='gallery.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['album', 'deleted_at'], name='gallery_pic_album_i_e4e993_idx'), models.Index(fields=['taken_at'], name='gallery_pic_taken_a_f86cb8_idx'), models.Index(fields=['is_favorite'], name='gallery_pic_is_favo_afc0f9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['owner', 'gallery_type'], name='gallery_gal_owner_i_4b36dc_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['deleted_at'], name='gallery_gal_deleted_df2ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['gallery', 'deleted_at'], name='gallery_alb_gallery_57def7_idx'),
        ),
    ]
