# Generated by Django 6.0.1 on 2026-01-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_picture_use_picturetag_through'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='picturetag',
            new_name='gallery_pic_picture_58a83a_idx',
            old_name='gallery_pictag_pic_src_idx',
        ),
    ]
