"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR points to /app (where manage.py is located)
BASE_DIR = Path(__file__).resolve().parent.parent
# Project root (one level up from app/)
PROJECT_ROOT = BASE_DIR.parent

# Load environment variables from .env file
# Try project root first (for local dev), then fall back to BASE_DIR
load_dotenv(BASE_DIR.parent / '.env')  # Project root
load_dotenv(BASE_DIR / '.env', override=False)  # App directory (fallback)

# Load YAML configuration
from .config_loader import get_config_loader
config = get_config_loader()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Uses DJANGO_SECRET_KEY env var or config.yaml django.secret_key
SECRET_KEY = config.get('django.secret_key', 'django-insecure-z&x2fgjdjshurb8*p9jtwlov@hy!_h&+obyi1(kl7u^#u5#dr$')

# SECURITY WARNING: don't run with debug turned on in production!
# Uses DJANGO_DEBUG env var or config.yaml django.debug
DEBUG = config.get_bool('django.debug', False)

# Uses DJANGO_ALLOWED_HOSTS env var or config.yaml django.allowed_hosts
ALLOWED_HOSTS = config.get_list('django.allowed_hosts', ['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Third-party
    'rest_framework',  # Django REST Framework
    
    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    
    # Local apps
    'gallery',
]

# Add storages if using S3/SeaweedFS
# Uses STORAGE_USE_S3 env var or config.yaml storage.use_s3
USE_S3 = config.get_bool('storage.use_s3', False)
if USE_S3:
    INSTALLED_APPS.append('storages')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add app-level templates directory (app/templates)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # Uses DATABASE_NAME, DATABASE_USER, etc. env vars or config.yaml
        'NAME': config.get('database.name', 'gallery'),
        'USER': config.get('database.user', 'postgres'),
        'PASSWORD': config.get('database.password', 'postgres'),
        'HOST': config.get('database.host', 'db'),
        'PORT': config.get('database.port', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = config.get('django.language_code', 'en-us')
TIME_ZONE = config.get('django.timezone', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = config.get('static_files.static_url', '/static/')
STATIC_ROOT = BASE_DIR / config.get('static_files.static_root', 'staticfiles')

MEDIA_URL = config.get('static_files.media_url', '/media/')
MEDIA_ROOT = BASE_DIR / config.get('static_files.media_root', 'media')

# SeaweedFS / S3 Storage Configuration
if USE_S3:
    # SeaweedFS S3-compatible storage
    # Uses STORAGE_S3_ACCESS_KEY_ID, STORAGE_S3_SECRET_ACCESS_KEY, etc. env vars or config.yaml
    AWS_ACCESS_KEY_ID = config.get('storage.s3.access_key_id', '')
    AWS_SECRET_ACCESS_KEY = config.get('storage.s3.secret_access_key', '')
    AWS_STORAGE_BUCKET_NAME = config.get('storage.s3.bucket_name', 'gallery')
    AWS_S3_ENDPOINT_URL = config.get('storage.s3.endpoint_url', 'http://seaweedfs:8333')
    AWS_S3_REGION_NAME = config.get('storage.s3.region_name', 'us-east-1')
    AWS_S3_USE_SSL = config.get_bool('storage.s3.use_ssl', False)
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    
    # Use S3 for media files
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication Configuration
AUTHENTICATION_BACKENDS = [
    # Django default authentication (username/password)
    'django.contrib.auth.backends.ModelBackend',
    # allauth authentication (social accounts)
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Site ID (required for allauth)
# Uses DJANGO_SITE_ID env var or config.yaml django.site_id
SITE_ID = config.get_int('django.site_id', 1)

# allauth Configuration
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Use email instead of username
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
# Uses AUTHENTICATION_ACCOUNT_EMAIL_VERIFICATION env var or config.yaml
ACCOUNT_EMAIL_VERIFICATION = config.get('authentication.account_email_verification', 'mandatory')
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
ACCOUNT_SESSION_REMEMBER = True

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = config.get('authentication.login_redirect_url', '/')
LOGOUT_REDIRECT_URL = config.get('authentication.logout_redirect_url', '/')

# Social Account Providers Configuration
SOCIALACCOUNT_PROVIDERS = {}

# Google OAuth
# Uses SOCIAL_AUTH_GOOGLE_ENABLED, SOCIAL_AUTH_GOOGLE_CLIENT_ID, etc. env vars or config.yaml
if config.get_bool('social_auth.google.enabled', False):
    SOCIALACCOUNT_PROVIDERS['google'] = {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': config.get('social_auth.google.client_id', ''),
            'secret': config.get('social_auth.google.secret', ''),
            'key': '',
        }
    }

# Facebook OAuth
# Uses SOCIAL_AUTH_FACEBOOK_ENABLED, SOCIAL_AUTH_FACEBOOK_APP_ID, etc. env vars or config.yaml
if config.get_bool('social_auth.facebook.enabled', False):
    SOCIALACCOUNT_PROVIDERS['facebook'] = {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id', 'first_name', 'last_name', 'middle_name',
            'name', 'name_format', 'picture', 'short_name', 'email',
        ],
        'EXCHANGE_TOKEN': True,
        'APP': {
            'client_id': config.get('social_auth.facebook.app_id', ''),
            'secret': config.get('social_auth.facebook.app_secret', ''),
            'key': '',
        }
    }

# GitHub OAuth
# Uses SOCIAL_AUTH_GITHUB_ENABLED, SOCIAL_AUTH_GITHUB_CLIENT_ID, etc. env vars or config.yaml
if config.get_bool('social_auth.github.enabled', False):
    SOCIALACCOUNT_PROVIDERS['github'] = {
        'SCOPE': ['user', 'user:email'],
        'APP': {
            'client_id': config.get('social_auth.github.client_id', ''),
            'secret': config.get('social_auth.github.secret', ''),
            'key': '',
        }
    }

# Celery Configuration
# Uses CELERY_BROKER_URL, CELERY_RESULT_BACKEND, etc. env vars or config.yaml
CELERY_BROKER_URL = config.get('celery.broker_url', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = config.get('celery.result_backend', 'redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = config.get_int('celery.task_time_limit', 1800)  # seconds
CELERY_TASK_SOFT_TIME_LIMIT = config.get_int('celery.task_soft_time_limit', 1500)  # seconds
CELERY_WORKER_PREFETCH_MULTIPLIER = config.get_int('celery.worker_prefetch_multiplier', 1)
CELERY_WORKER_MAX_TASKS_PER_CHILD = config.get_int('celery.worker_max_tasks_per_child', 1000)

# Celery Queue Configuration
# Separate queues for CPU and GPU tasks
CELERY_TASK_ROUTES = {
    # Route GPU-intensive tasks (YOLO, PaddleOCR) to GPU queue
    # Example: 'gallery.tasks.process_image_with_gpu': {'queue': 'gpu'},
    # Route CPU tasks to CPU queue
    # Example: 'gallery.tasks.process_metadata': {'queue': 'cpu'},
}
CELERY_TASK_DEFAULT_QUEUE = 'cpu'  # Default queue for tasks without explicit routing
CELERY_TASK_DEFAULT_EXCHANGE = 'tasks'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'cpu'

# Gallery App Configuration
GALLERY_MEDIA_BASE_URL = config.get('gallery.media_base_url', '/media')
GALLERY_SIGNED_URL_SECRET = config.get('gallery.signed_url_secret', None)  # Optional, falls back to SECRET_KEY
GALLERY_SIGNED_URL_EXPIRES_IN = config.get_int('gallery.signed_url_expires_in', 3600)  # 1 hour default

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}
